### ISSUE TITLE
Only certain amenities show on app and reword amenity titles

### ISSUE THREAD

**Issue by trbmcginnis** [NYCPlanning/labs-waterfront-access#65] opened 2018-10-15 13:53 UTC
Talk to planners and filter down which amenities we want to show. 

Also, change wording to better demonstrate to members of the public what is actually in the park. (e.g. "ground cover" --> "public lawn")

**Comment by hannahkates** [comment] 2018-10-16 14:37
Dupe of #33

**Closed by hannahkates** 2018-10-16 14:37 UTC
Labels: current sprint, need clarification
